{% load django_coalesce %}"""Generated by django-coalesce. DO NOT EDIT."""

export interface {{ model.model_name }} {
    {% spaceless %}
    {% for field in model.fields %}{{ field.name }}: {{ field|to_typescript_type }};
    {% endfor %}
    {% endspaceless %}
}
